### ISSUE TITLE
Runtime limit issue with 3.0

### ISSUE THREAD

**Issue by viennej** [hpcg-benchmark/hpcg#39]
I noticed that the last line of hpcg.dat doesn’t seem to be used as a runtime limit by HPCG 3.0.
Before 3.0, when the value was set to 1200, I was able to run HPCG during at least 20 minutes.
But, with the 3.0 (HPCG 3.0 Reference Code), the same input only run for 166 seconds.
It looks like that using --rt=1200 fixed the issue but I believe that there is a bug with this last parameter inside hpcg.dat.

**Comment by wohlbier** [comment]
Line 97 of init.cpp

`if (! iparams[3]) rt = 0; // If --rt was specified, we already have the runtime, so don't read it from file`

should be

`if (iparams[3]) rt = 0; // If --rt was specified, we already have the runtime, so don't read it from file`
