### ISSUE TITLE
Bugs in SparseMatrix C++11 checks for map selection

### ISSUE THREAD

**Issue by mneilly** [hpcg-benchmark/hpcg#43]
SparseMatrix.hpp contains two bugs in the following C++ version check as of commit 299047b84897132bdda57ede242760dea6d4fd23:

```
#if __cplusplus <= 201103L
// for C++03
#include <map>
typedef std::map< global_int_t, local_int_t > GlobalToLocalMap;
#else
// for C++11 or greater
#include <unordered_map>
using GlobalToLocalMap = std::unorderd_map< global_int_t, local_int_t >;
#endif
```

The check of __cplusplus performs a less than or equal check which should be a less than check. As it is written passing -std=c++11 to g++ causes the "// for C++03" code to be used. 

In the "// for C++11 or greater" code, std::unordered_map is incorrectly spelled as std::unorderd_map. It is missing the e between the r and d.

**Comment by luszczek** [comment]
Fixed in 002fc8c94a7a8ea64ad39e63906b6ee00161d3ee
