### ISSUE TITLE
Use of [] operator in CheckProblem with HPCG_DEBUG_DETAILED

### ISSUE THREAD

**Issue by mneilly** [hpcg-benchmark/hpcg#44]
CheckProblem.cpp declares the A SparseMatrix argument as const:

`void CheckProblem(const SparseMatrix & A, Vector * b, Vector * x, Vector * xexact) {
`

Later, std::cout is used to display the local row using `A.globalToLocalMap[currentGlobalRow]`.

Since A is declared as const the [] operator cannot be used because it may insert a new entry if one does not exist.

The following:

```
#ifdef HPCG_DETAILED_DEBUG
        HPCG_fout << " rank, globalRow, localRow = " << A.geom->rank << " " << currentGlobalRow << " " << A.globalToLocalMap[currentGlobalRow] << endl;                                     
#endif
```

can be replaced in C++11 with:

```
#ifdef HPCG_DETAILED_DEBUG
    HPCG_fout << " rank, globalRow, localRow = " << A.geom->rank << " " << currentGlobalRow << " " << A.globalToLocalMap.at(currentGlobalRow) << endl;
#endif
```

or prior to C++11 with:

```
#ifdef HPCG_DETAILED_DEBUG
        HPCG_fout << " rank, globalRow, localRow = " << A.geom->rank << " " << currentGlobalRow << " " << A.globalToLocalMap.find(currentGlobalRow)->second << endl;
#endif

```

**Comment by luszczek** [comment]
Fixed in 2cbf210457a165ad701dfdf701052edb9583126a
