### ISSUE TITLE
HPCG 3.0- Assertion nxf%2==0 failed.

### ISSUE THREAD

**Issue by puneet336** [hpcg-benchmark/hpcg#47]
#Dear All,
I have compiled HPCG benchmark with intel 2016 parallel studio XE for Xeon(R) CPU E5-2680 (RHEL 6.6). I have 64 GB of memory installed on my machine. Also, my hpcg.dat file is :
```
HPCG Linpack benchmark input file
Sandia National Laboratories, University of Tennessee
430 430 430
1200
```

With this configuration , the xhpcg binary occupies 83% of memory but after ~ 13 minutes the run crashes with error:
xhpcg: src/GenerateCoarseProblem.cpp:50: void GenerateCoarseProblem(const SparseMatrix_STRUCT &): Assertion `nxf%2==0' failed.

Could you please let me know where i am going wrong with the configurations?

**Comment by LWisteria** [comment]
I'm not a HPCG main developer but I know the local size should be divisible by 8 because HPCG uses 4-level multigrid preconditioner.
How about 432x432x432 or 424x424x424 instead of 430x430x430?

**Comment by puneet336** [comment]
Hi,
Thanks for the quick reply
With hpcg.dat as:-
424 424 424
1200

the simulation completed within  115m7.580s. I got the following data:-
```
GFLOP/s Summary:
  Raw DDOT: 9.54469
  Raw WAXPBY: 4.74248
  Raw SpMV: 6.57449
  Raw MG: 0.665184
  Raw Total: 0.792704
  Total with convergence overhead: 0.792704
  Total with convergence and optimization phase overhead: 0.773687
...................
__________ Final Summary __________:
  HPCG result is VALID with a GFLOP/s rating of: 0.773687
      HPCG 2.4 Rating (for historical value) is: 0.792703

```
Though with HPL i get approx  7.62620e+02 Gflops (for N=83328   NB=192    P=1    Q=1             505.81 )           
HPCG number(0.773Gflops) are way too off from what i usually get via HPL (~780Gflops)

Or am i wrong on my observations here?

**Comment by luszczek** [comment]
HPCG uses multigrid preconditioner with three levels. Each level requires division by 2. So your original problem size has to be divisible by 8 (=2*2*2).
Performance observed with HPCG is not meant to track HPL. In fact, HPCG achieves a fraction of HPL achieves. Please see HPCG web site and look at the results pages that show what that fraction is for machines around the world.
