### ISSUE TITLE
Consider a replacement for YAML output

### ISSUE THREAD

**Issue by maherou** [hpcg-benchmark/hpcg#5]
Capturing a comment from Piotr Luszczek:

PS. My real headache comes from YAML. All versions so far generated
YAML with first line not being YAML. On top of that, YAML is nice
to look at with a text editor that submitters edit it by hand and
add new sections. All of it is not valid YAML and things break.
I fixed it in the reference code so now YAML parsers work with HPCG
output. But we have old versions generating problematic first line.
We have Intel/NVIDIA/IBM codes that generating additional things
that are not up to YAML standard.

I was thinking of switching to something less easy to "break" by
manual editing. JSON could get complex but it's popular. For HPCC
we used key-value pairs and we kept adding new pairs as needed.

Currently, I have to be permissive when taking in the YAML-looking
input. And it might be OK.

In the end, it's a minor issue.

**Comment by luszczek** [comment]
I committed the change as dc30fc219e1b81729eb403949db3b600fc29de92

**Comment by giraldeau** [comment]
The documentation in QUICKSTART indicates that the benchmark outputs YAML, but it isn't. Maybe there can have a switch to choose the output format.

**Comment by luszczek** [comment]
I have fixed the QUICKSTART issue with 02814129e82875fae98ee69a450b60ec35c02be7
