### ISSUE TITLE
std::map type unmatched in SetupHalo_ref.cpp

### ISSUE THREAD

**Issue by huanghua1994** [hpcg-benchmark/hpcg#50]
In SetupHalo_ref.cpp, the definition of `externalToLocalMap` is `std::map<local_int_t, local_int_t>. However, line 147 and 152 use a `global_int_t` as the key of the map. `externalToLocalMap` should be `std::map<global_int_t, local_int_t>`

**Comment by luszczek** [comment]
Fixed by 134fe80c702f881ffe8a83ba6c8bf6a6d1849253
