### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by haozewu** [hpcg-benchmark/hpcg#55]
# error
I use setup/Make.Linux_MPI to set and ../configuration <aech> in build/
but when I type "make" in build/
there is an error
```
/mpich/include: file not recognized: Is a directory
collect2: error: ld returned 1 exit status
```
in the INSTALL file
there is
```
* ``MPinc`` specifies the path to include directories with MPI header files. A
  common setting here would be ``MPinc = $(MPdir)/include``, provided that the
  ``MPdir`` variable was set properly.
```
# solution
Add "-I" before $(MPdir)/include

**Comment by ZouYiHAO** [comment]
hi,I wanna ask a question about the version HPCG 3.1,I only can change the numbers of nx ny nz to optimize the result,How to have a better result?THANKS

**Comment by luszczek** [comment]
You you need to use -I$(MPdir)/include
