### ISSUE TITLE
Unit tests in `unittesting` directory fail to compile

### ISSUE THREAD

**Issue by alfredo-gimenez** [hpcg-benchmark/hpcg#56]
Looks like the unit tests use an older(?) version of HPCG, and the current function signatures don't match. For example:

```cpp
int ReadHpcgDat(int *localDimensions, int *secondsPerRun, int *localProcDimensions);
```

...is [called with too few arguments](https://github.com/hpcg-benchmark/hpcg/blob/master/unittesting/hpcg_dat/main.cpp#L39):

```cpp
ReadHpcgDat(localDims, &seconds);
```

and similarly the  function:

```cpp
void GenerateGeometry(int size, int rank, int numThreads, int pz, local_int_t zl, local_int_t zu, local_int_t nx, local_int_t ny, local_int_t nz, int npx, int npy, int npz, Geometry * geom);
```

...is [also called with too few arguments](https://github.com/hpcg-benchmark/hpcg/blob/master/unittesting/Geometry/main.cpp#L42):

```cpp
GenerateGeometry(size, rank, numThreads, nx, ny, nz, geom)
```

Maybe the unittests are considered deprecated and should be removed?

**Comment by alfredo-gimenez** [comment]
Possible fix, if these aren't deprecated, is to provide defaults for the numbers of processors to 1, since these are probably run in serial.

**Comment by luszczek** [comment]
No Makefile for `unittesting` yet because the tests are not suppose to build yet.
