### ISSUE TITLE
I get a problem in the build step 

### ISSUE THREAD

**Issue by Bohemianman** [hpcg-benchmark/hpcg#57]
I am a beginner and  my English is not very good.  But I hope you can take some time to answer my doubts. I will be very grateful
  I have clone it from Github.com.Then I choose hpcg/setup/Make.linux_MPI . Copy and paste it to setup.
  And I have change something about it.
MPdir        = $(HOME)mpich
MPinc        = -I$(MPdir)/include
MPlib        = $(MPdir)/lib
HPCG_OPTS     = -DHPCG_NO_OPENMP
CXX          = $(HOME)mpich/bin/mpicc
LINKER       = $(HOME)mpich/bin/mpicc
LINKFLAGS    = $(HOME)mpich/bin/mpicc
  Then I want to start the next step.   In top-level directory, type:    make path/to/setup/file
  It says:  make: *** No rule to make target 'path/to/setup/file'
   I really want to know how to solve this problem.
  If you can answer It I will be greatly appreciated.

**Comment by luszczek** [comment]
You need to type `make arch=linux_MPI` so your file is found correctly.
