### ISSUE TITLE
If the --rt parameter is read from file, it does not get used

### ISSUE THREAD

**Issue by tonimctoni** [hpcg-benchmark/hpcg#59]
In `init.cpp` line 99 `ReadHpcgDat(iparams, rt, iparams+7);` reads the --rt parameter into the `rt` variable, which does not get used anywhere else. This means that specifying it in the `hpcg.dat` file has no effect.

Furthermore, `ReadHpcgDat` only reads this parameter if `rt != 0`, but `rt` is 0 if `iparams[3]==0`, which is the default value. This means that that if the --rt parameter is not set via the command line arguments, it is not read from `hpcg.dat` either.

**Comment by luszczek** [comment]
Fixed by b8bd9d90e2e34043ba77be4db89e707a8e70877c
