### ISSUE TITLE
HPCG Memory Output

### ISSUE THREAD

**Issue by ikarlin** [hpcg-benchmark/hpcg#62]
The memory output from HPCG is a base 10 value.  This is for both the GB and GB/s.  The end result is confusing since systems are speced in GiB and standard benchmarks, such as Stream measure bandwidth in GiB/s.  Having to do this conversion is both error prone and it is not always obvious to users that they need to convert their data.  This causes potential issues when using the code as a benchmark in some contexts.

I suggest converting to the standard base 2 GiB.

**Comment by luszczek** [comment]
From what I can see, bandwidth is measured in 10-base units (STREAM and MPI benchmarks).
Network hardware (WiFi and Ethernet) uses bits per second but also base-10 prefixes.
Only storage seems to be measured in 2-based units as long it's not consumer-grade.
Consumer storage still uses 10-base units that are sometimes confused with 2-based units.

We could consider switching to reporting data sizes with 2-based prefixes.

But bandwidth and Giga-flops rates are in line with the common practice.

**Comment by ikarlin** [comment]
Sorry for the slow response.  While you are right about MPI and other network benchmarks you are wrong about STREAM.  STREAM reports in base 2 units.  See https://www.cs.virginia.edu/stream/FTP/Code/stream.c

**Comment by luszczek** [comment]
Thank you. I think we reached an agreement. Sizes in GiB and bandwidth in GB/s. As in STREAM: lines 237 and 367, respectively.

**Comment by ikarlin** [comment]
Sure that works.
