### ISSUE TITLE
Volta-enabled HPCG compilation

### ISSUE THREAD

**Issue by afernandezody** [hpcg-benchmark/hpcg#63]
Hello,
I downloaded the Volta-enabled tar/binary file (hpcg-3.1_cuda9_ompi1.10.2_gcc485_sm_35_sm_50_sm_60_sm_70_ver_10_8_17.tgz) from the official website. The thing is that some elements (compiler, CUDA & ompi) are a bit outdated. Would it be possible to add a Github branch with the CUDA version so that users can build the code based on their system characteristics? Thanks.

**Comment by luszczek** [comment]
NVIDIA provides only binaries for their HPCG implementation. And there are currently no plans to have source code available.
