### ISSUE TITLE
Undefined data attribute in parallel region with default(none)

### ISSUE THREAD

**Issue by mcordery** [hpcg-benchmark/hpcg#64]
https://github.com/hpcg-benchmark/hpcg/blob/e3fe052b572b5e512a826769834582fc1939389c/src/ComputeResidual.cpp#L56

Note that the variable 'n' in the referenced for loop is passed as a const variable to the function but that default(none) is set on the loop and the variable is not in the shared() attribute list. This will throw an error at least with g++ 9.2

**Comment by luszczek** [comment]
Closed by e9e0b7e

**Comment by luszczek** [comment]
We will need to guard against inconsistency of treating OpenMP attributes in GCC 8 and 9
