### ISSUE TITLE
Add peak system bandwidth to website submission form

### ISSUE THREAD

**Issue by maherou** [hpcg-benchmark/hpcg#7]
We should add a question to the online submission form asking for the peak system memory bandwidth.  This number will be reported and used to report the fraction of peak bandwidth we achieved.

**Comment by luszczek** [comment]
It will be added soon.
Question: is it "total" memory bandwidth? Or "per-core" bandwidth?
How should it be calculated for some common processors? I'm afraid practitioners will put the right answer but most others folks will mess it up.
There is also the question of accelerators: do we report two bandwidth values?

**Comment by maherou** [comment]
Can we use the STREAMS metric for the whole system?  I think this is what most people would want to know.  The HPCG bandwidth metric is the observed total system bandwidth for the CG phase.  I use an idealized model such that each array is assumed to be read/written once per operation.  For example, the read/write counts for SpMV (y = Ax) assumes that x is read once (8n bytes, where n is the global problem dimension) and y is written once (also 8n bytes).

**Comment by maherou** [comment]
This has been added to the online submission form.
