### ISSUE TITLE
HPCG Cuda Binary with multiple GPUs?

### ISSUE THREAD

**Issue by tcarneirop** [hpcg-benchmark/hpcg#77]
Hello,

I am trying to run HPCG (xhpcg-3.1_cuda-11) on a multi-GPU computer.

However, when I run it on a two-GPUs node,  the code is only executed on only one GPU.

What are the command line parameters to tell the application to run the code on multiple GPUs?

Finally, I would like to know how if there is a documentation for the ./xhpcg-3.1_cuda-11_ompi-4.0_sm_60_sm70_sm80 binary.

Thank you and best regards,

Tiago Carneiro

**Comment by luszczek** [comment]
I would first suggest to use NVIDIA's HPC-Benchmark container from NVIDIA's NGC collection at https://catalog.ngc.nvidia.com/orgs/nvidia/containers/hpc-benchmarks because they have `--config` option with presets for multi-GPU nodes. The binary you reference is no longer maintained by NVIDIA.

**Comment by tcarneirop** [comment]
Hello Piotr, 

thank you.

I see. However, I could not run this container they provide and I would like just to run the binary for some comparison purposes.

Do you know the parameters to pass to the binary so the code get executed on multiple gpus?

Thank you and best regards,

Tiago Carneiro

**Comment by luszczek** [comment]
The binary code from HPCG software page expects one GPU per MPI rank. So you should have as many MPI ranks as you have GPUs on your node. The MPI message will not use the network since the MPI ranks will all be sharing the same main memory space.

**Comment by tcarneirop** [comment]
Dear Piotr,

Thank you! Would it be possible to ask to add this information to the documentation?

**Comment by luszczek** [comment]
Done. Great suggestion, thanks!
