### ISSUE TITLE
Number of OMP Threads for MPI_GCC_OMP 

### ISSUE THREAD

**Issue by tcarneirop** [hpcg-benchmark/hpcg#78]
Dear, I would like to know the correct number of OMP threads one should use per MPI rank to run the MPI_GCC_OMP version.

The "Quickstart" documentation suggests OMP_NUM_THREADS 4. However, the AMD documentation suggests 2 per MPI rank.

Thank you,

Tiago Carneiro

**Comment by jdayal-ssi** [comment]
That totally depends on your exact architecture. You will have to play around with different permutations to find the "best" version.

**Comment by luszczek** [comment]
HPCG code is meant to run with one or many OpenMP threads. At the same time, the reference implementation is meant for using one or many MPI ranks. And the reference code is meant to build on systems with no OpenMP nor MPI for maximum flexibility of understanding the code base and running basic tests. It is hard to recommend a particular number of threads and ranks for a particular system without knowing more details about the distribution of the threads (per cache level, per-socket, or per NUMA island). The MPI ranks could be distributed across a single node and thus might conflict with the thread counts. The use of hardware accelerators such as GPUs complicates this picture even harder. So please refrain from recommending a particular configuration to be applicable in general for many systems.
