### ISSUE TITLE
Hello. How to generate trace for HPCG?

### ISSUE THREAD

**Issue by szuhzw** [hpcg-benchmark/hpcg#83]

**Comment by luszczek** [comment]
Could you please provide more details as to what kind of trace you'd like to get?

**Comment by luszczek** [comment]
Depending on the platform, there are plenty of tools available such as TAU, Vimpir, Intel Analyzer, NVIDIA Visual Profiler, or AMD's ROCProfiler. Select the one that works best for your hardware and software setup.
